name: Terraform cicd pipeline workflow
on:
 push:
  branches: [main,feature/*]
 pull_request:
  branches: [main]
 workflow_dispatch:
jobs:
 terraform:
   name: Terraform-cicd
   runs-on: ubuntu-latest
   steps:
   - name: checkout code
     uses: actions/checkout@v4
   - name: configure aws credentials
     uses: aws-actions/configure-aws-credentials@v3
     with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
   - name: setup terraform
     uses: hashicorp/setup-terraform@v2
     with:
      terraform_version: 1.5.0
   - name: Terraform initialisation
     run: terraform init
   - name: Terraform plan
     run: terraform plan -out tfplan
 